FROM gradle:jdk20-alpine as builder
COPY . .
RUN gradle build
RUN mv app/build /

FROM openjdk:20 as java
RUN microdnf install findutils
COPY --from=builder /build/distributions/app.tar /
RUN tar -C / -xvf /app.tar
WORKDIR /app
COPY app/.env.docker ./.env
CMD /app/bin/app
