services:
  mariadb:
    restart: unless-stopped
    image: mariadb:11.1
    environment:
      MARIADB_ROOT_PASSWORD: $DB_ROOT_PASSWORD
      MARIADB_DATABASE: $DB_NAME
      MARIADB_USER: $DB_USER
      MARIADB_PASSWORD: $DB_PASSWORD
    volumes:
      - db:/var/lib/mysql
  java:
    depends_on:
      - mariadb
    restart: unless-stopped
    image: $DOCKER_REGISTRY/todo-back-java:$SHORT_SHA
    ports:
      - $PORT:$PORT
#  nginx:
#    restart: unless-stopped
#    image: nginx
#    ports:
#      - 80:80

volumes:
  db: