/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package test;

import test.services.database.MongoDb;

public class App {
    public static void main(String[] args) {
        // Init database connection
        try {
            init();
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }

    private static void init() throws Exception {
        MongoDb.init();
        System.out.println("Connected to database successfully");

    }
}
