/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package test;

import org.bson.Document;
import test.services.database.MongoDb;

public class App {
    public static void main(String[] args) {
        // Init database connection
        try {
            init();
        } catch (Exception e) {
            System.out.println(e.getMessage());
            return;
        }

        Document doc = MongoDb.findFirstDocument("test", "name", "test");
        System.out.println(doc.toJson());
    }

    private static void init() throws Exception {
        MongoDb.init();
    }
}
